### ISSUE TITLE
Code taken from World Models

### ISSUE THREAD

**Issue by TrentBrick** [sksq96/pytorch-mdn#3]
I just left an issue on your other repo for your PyTorch CNN VAE and am going to leave the exact same one here. 

"Hey thanks for having this code up.

However, I have realized that it is almost completely identical to David Ha's World Models research https://arxiv.org/pdf/1803.10122.pdf and code including the code here: https://github.com/ctallec/world-models

Please give credit where credit is due."

**Comment by TrentBrick** [comment]
I will be notifying David Ha directly if you don't assign the proper credit or explain why your code is different (even though it happens to look so similar).

**Comment by sksq96** [comment]
Re: https://github.com/sksq96/pytorch-vae/issues/5

**Comment by sksq96** [comment]
As per the code, I went to https://github.com/ctallec/world-models/commits/master?after=d6abd9ce97409734a766eb67ccf0d1967ba9bf0c+104 to check the commit history. His codebase was started (May 2018) after my code was committed (April 2018). See https://github.com/sksq96/pytorch-vae/commits/master.  

Please do thorough research before bringing up accusations of these sorts.

**Comment by TrentBrick** [comment]
Thank you for updating your READMEs here and in the VAE code. 

I brought up https://github.com/ctallec/world-models only to highlight the similarities between your code and the World Models code (this is a better comparison than the open source world models code from David Ha himself as that is written in Tensorflow as I'm sure you know.) I was not trying to suggest you had taken any code from them and sorry it came off that way.
